version: '3.11'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data:/var/lib/postgresql/data

    env_file:
      - .env
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    hostname: '${DB_HOST}'

  web:
    build:
      dockerfile: _docker/Dockerfile
    restart: always
    command: bash -c "python main.py"
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env


volumes:
  db_value: